routes/web.php
<?php
use Intervention\Image\Facades\Image;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Route::resource('contact','ContactController');
Route::resource('membership','MembershipController');
Route::resource('home','HomeController');
Route::resource('page','PageController');
Route::resource('event','EventController');

Route::post('/apply', 'ApplyController@apply')->name('appy');


Route::get('storage/profile/photos/{filename}', function ($filename) {
    return Image::make(storage_path('profile/photos/' . $filename))->response();
});

Route::get('storage/logo/{filename}', function ($filename) {
    return Image::make(storage_path('logo/' . $filename))->response();
});

resources/views/contact.blade.php
<html>
  <head>
    <!-- BEGIN HEADER -->
@include('partials.head')
<!-- END HEADER -->
</head>
  <body class="pace-black  mac desktop pace-done"><div class="pace  pace-inactive"><div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
  <div class="pace-progress-inner"></div>
</div>
<div class="pace-activity"></div></div>
    <!-- BEGIN HEADER -->
    @include('partials.navbar')
    <!-- END HEADER -->
    <section class="m-t-100 sm-m-t-230">
      <!-- START CONTACT SECTION -->
      <section class="container container-fixed-lg p-t-50 p-b-80  sm-p-t-30 sm-p-b-30">
<div class="row">
<div class="col-md-5">
<div class="row">
<div class="col-sm-6 col-md-12">
<h4>How can we assist you? <br></h4>
</div>
<div class="col-sm-6 col-md-12">

<p>If you wish to talk to someone regarding membership please use the form below to send a message to WAC. </p>
</div>
<div class="col-sm-6 col-md-12">
  <h4>Setting up a Local WAC group?</h4>
  </div>
  <div class="col-sm-6 col-md-12">

    <p>We are keen to set up new local groups accross the westcountry.  If you feel that you would like to start a group in Cornwall or North Devon, in particular, then please do get in touch.</p>
    <p>We are able to offer some financial support and it is easier than you may think to set up a group and someone will be there in the back ground to support you.</p>
  </div>
</div>
</div>
<div class="col-md-7">


<h4 class="sm-m-t-20">Contact us below</h4>
<!-- will be used to show any messages -->
  @if (Session::has('message'))
      <div class="alert alert-info"><h5> {{ Session::get('message') }} </h5></div>
  @endif
<form class="" role="form" action="{{ route('contact.store') }}" method="post">
  @csrf
<div class="row">
<div class="col-sm-6">
<div class="form-group form-group-default">
<label>First name</label>
<input type="text" class="form-control" name="fname" required>
</div>
</div>
<div class="col-sm-6">
<div class="form-group form-group-default">
<label>Last name</label>
<input type="text" class="form-control" name="lname" required>
</div>
</div>
</div>
<div class="form-group form-group-default">
  <label>Email</label>
  <input type="email" placeholder="Enter your email address" class="form-control" name="email" required>
  </div>
    <div class="form-group form-group-default">
        <label>Recipient</label>
        <select class="form-control" id="exampleFormControlSelect1" name="recipient" required>
          <option value="Vice Chair">Vice Chair</option>
          <option value="Chair">Chair</option>
          <option value="Treasurer">Treasurer</option>
          <option value="Membership Secretary">Membership Secretary</option>
          <option value="Secretary">Secretary</option>
          <option value="Journal & Newsletter Editor">Journal & Newsletter Editor</option>
          <option value="Web Coordinator">Web Coordinator</option>
          <option value="Exeter Representative">Exeter Representative</option>
          <option value="Plymouth Representative">Plymouth Representative</option>
          <option value="Tavistock Representative">Tavistock Representative</option>
          <option value="Cornwall Representative">Cornwall Representative</option>
        </select>
      </div>
    <div class="form-group form-group-default">
      <label>Subject</label>
      <input type="text" placeholder="What is this regarding?" class="form-control" name="subject" required>
      </div>
<div class="form-group form-group-default">
<label>Message</label>
<textarea class="form-control" style="height:100px" placeholder="Type the message you want inquire" name="message" required></textarea>
</div>
<p class="pull-left  small hint-text m-t-5 font-arial sm-m-t-10">I hereby certify that the information above is true and accurate. </p>
<button class="btn btn-white font-montserrat all-caps fs-11 pull-right sm-m-t-10" type="submit">Send request</button>
<div class="clearfix"></div>
</form>
</div>
</div>
</section>
    <!-- END SECION -->
    @include('partials.footer')
    <!-- BEGIN SCRIPTS -->
    @include('partials.scripts')
    <!-- END SCRIPTS -->
</section></body></html>

resources/views/eventdetail.blade.php
<html>

<head>
    <!-- BEGIN HEADER -->
    @include('partials.head')
    <!-- END HEADER -->
</head>

<body class="pace-black  mac desktop pace-done">
    <div class="pace  pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
    </div>
    <!-- BEGIN HEADER -->
    @include('partials.navbar')
    <!-- END HEADER -->
    <section class="m-t-100 sm-m-t-40">
        <section class="p-b-50 p-t-50">
            <div class="container">
                <div class="panel panel-transparent">
                    <div class="tab-content bg-white ">
                        <div class="row p-l-20 p-r-20 p-b-20 p-t-5 xs-no-padding">
                            <div class="col-md-11">
                                <div class="tab-pane active" id="tab3hellowWorld">
                                    
                                <!-- will be used to show any messages -->
                    @if (Session::has('message'))
                                    <div class="alert alert-info"><h5> {{ Session::get('message') }} </h5></div>
                    @endif
                    
                                        <h3>{!!$event->title!!}</h3>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">Event Host:  <span class="badge badge-light">{{$event->user->name}} </span></li>
                                            <li class="list-inline-item">Venue Name:  <span class="badge badge-info">{{$event->venue->name}} </span> </li>
                                            <li class="list-inline-item">City located:  <span class="badge badge-success">{{$event->page->title}} </span></li>
                                        </ul>
                                    <br>
                                <div class="m-t-15">
                                       {!!$event->description!!}

                                </div>
                                    <br/>
                                    <div>
                                        <p>
                                            <b>Open To</b>: {!!$event->open_to!!}
                                        </p>
                                        <p>
                                            <b>Cost for Member</b>: £{!!$event->cost_for_member!!}
                                        </p>
                                        <p>
                                            <b>Cost for Non-Member</b>: £{!!$event->cost_for_non_member!!}
                                        </p>
                                        <p>
                                            <b>Date</b>: {!!$event->date!!}
                                        </p>
                                        <p>
                                            <b>Start Time</b>: {!!$event->start_time!!}
                                        </p>
                                        <p>
                                            <b>End Time</b>: {!!$event->end_time!!}
                                        </p>
                                        <p>
                                            <b>Venue</b>: {{$event->venue->name}} <br>{{$event->venue->address}}
                                        </p>
                                        <br>
                                        @php
                                        $date = new DateTime($event->date);
                                        $now = new DateTime();
                                        @endphp
                                        @if ($date < $now)
                                        @elseif($event->online_booking == 'Disable')
                                        <h1 class="alert alert-info">Booking is not necessary for this event.</h1>
                                        @elseif ($date < $now)
                                        
                                        @elseif ($event->cost_for_non_member > 0)
                                        <p>
                                                <form action="{{ route('appy') }}" method="POST">
                                                    {{ csrf_field() }}
                                                <input type="hidden" name="event_id" value="{{$event->id}}">
                                                    <script
                                                            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                                            data-key="pk_test_ks9An34uZO8eHyZswCiQhIyQ"
                                                            data-name="W.A.C"
                                                            data-label = "Book Now"
                                                            data-description="Online Event Booking"
                                                            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                                                            data-locale="auto">
                                                    </script>
                                                </form>
                                            </p>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!-- END SECION -->
    @include('partials.footer')
    <!-- BEGIN SCRIPTS -->
    @include('partials.scripts')
    <!-- END SCRIPTS -->
    </section>
</body>

</html>

resources/views/events.blade.php
<html>

<head>
    <!-- BEGIN HEADER -->
    @include('partials.head')
    <!-- END HEADER -->
</head>

<body class="pace-black  mac desktop pace-done">
    <div class="pace  pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
    </div>
    <!-- BEGIN HEADER -->
    @include('partials.navbar')
    <!-- END HEADER -->
    <section class="m-t-100 sm-m-t-40">
        <!-- START CONTACT SECTION -->
        <section class="container container-fixed-lg p-t-50 p-b-80  sm-p-t-30 sm-p-b-20">
            <h1>Events Calendar<br></h1>
            <P>When booking an event please be sure to sumbit dietary requirements in the ADDITI0NAL INFORMATION BOX, no later than 7 days before the event.
                <br> <br> If you are making bookings for more than 1 could you state the name of the 'other' attending in the ADDITIONAL INFORMATION BOX also, for CPD Certificate purposes. with much apprecieaation WAC.
                <P>
                    <div class="bd-example">
                        <table class="table table-bordered table-dark">
                            <thead>
                                <tr>
                                    <th scope="col">Date</th>
                                    <th scope="col">Events (click for details & booking)</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach ($events as $event)
                                <tr>
                                    <th scope="row">{{$event->date}}</th>
                                    <td>
                                        <a href="{{('/event/'.$event->id)}}">{{$event->title}}</a>
                                        <br>{{$event->event_group}} Open to {{$event->open_to}}. Cost for Member: £{{$event->cost_for_member}}. Cost for Non-Member: £{{$event->cost_for_non_member}}. <span class="badge badge-success">{{$event->page->title}} </span>                                        <span class="badge badge-info">{{$event->venue->name}} </span>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
        </section>
        <!-- END SECION -->
        @include('partials.footer')
        <!-- BEGIN SCRIPTS -->
        @include('partials.scripts')
        <!-- END SCRIPTS -->
    </section>
</body>

</html>

resources/views/grouppage.blade.php
<html>

<head>
    <!-- BEGIN HEADER -->
    @include('partials.head')
    <!-- END HEADER -->
</head>

<body class="pace-black  mac desktop pace-done">
    <div class="pace  pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
    </div>
    <!-- BEGIN HEADER -->
    @include('partials.navbar')
    <!-- END HEADER -->
    <section class="m-t-100 sm-m-t-35">
        <section class="p-b-50 p-t-35">
            <div class="container">
                <div class="panel panel-transparent">
                    <ul class="nav nav-tabs nav-tabs-simple nav-tabs-left bg-white" id="tab-3">
                        <li>
                                    {!!$page->name!!}
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content bg-white ">
                        <div class="row p-l-20 p-r-20 p-b-20 p-t-5 xs-no-padding">
                            <div class="col-md-11">
                                <div class="tab-pane active" id="tab3hellowWorld">
                                        {!!$page->description!!}
                                        <br><br><br>
                                        <table class="table table-bordered table-dark">
                                            <thead>
                                              <tr>
                                                <th scope="col">Date</th>
                                                <th scope="col">Events (click for details & booking)</th>
                                              </tr>
                                            </thead>
                              
                                            <tbody>
                                              @foreach ($events as $event)
                                              <tr>
                                              <th scope="row">{{$event->date}}</th>
                                                <td>
                                                  <a href="{{('/event/'.$event->id)}}">{{$event->title}}</a>
                                                  <br>{{$event->event_group}} Open to {{$event->open_to}}. Cost for Member: £{{$event->cost_for_member}}. Cost for Non-Member: £{{$event->cost_for_non_member}}. <span class="badge badge-success">{{$event->page->title}} </span> <span class="badge badge-info">{{$event->venue->name}} </span>
                                                </td>
                                              </tr>
                                              @endforeach
                                            </tbody>
                                          </table>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!-- END SECION -->
    @include('partials.footer')
    <!-- BEGIN SCRIPTS -->
    @include('partials.scripts')
    <!-- END SCRIPTS -->
    </section>
    </body> </html>

resources/views/index.blade.php
<html>

<head>
  <!-- BEGIN HEADER -->
  @include('partials.head')
  <!-- END HEADER -->
</head>

<body class="pace-black  mac desktop pace-done">
  <div class="pace  pace-inactive">
    <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
      <div class="pace-progress-inner"></div>
    </div>
    <div class="pace-activity"></div>
  </div>
  <!-- BEGIN HEADER -->
  @include('partials.navbar')
  <!-- END HEADER -->
  <section class="m-t-100 sm-m-t-30">
    <!-- BEGIN INTRO CONTENT -->
    @include('partials.events')
    <!-- END INTRO CONTENT -->
    <section class="p-b-50 p-t-50">
      <div class="container">
        <div class="panel panel-transparent">
          <ul class="nav nav-tabs nav-tabs-simple nav-tabs-left bg-white" id="tab-3">
          </ul>
          <div class="tab-content bg-white ">
            <div class="row p-l-20 p-r-20 p-b-20 p-t-5 xs-no-padding">
              <div class="col-md-11">
                <div class="tab-pane active" id="tab3hellowWorld">
                  {!!$home->description!!}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- END SECION -->
    @include('partials.footer')
    <!-- BEGIN SCRIPTS -->
    @include('partials.scripts')
    <!-- END SCRIPTS -->
  </section>
</body>

</html>

resources/views/joinus.blade.php
<html>

<head>
  <!-- BEGIN HEADER -->
  @include('partials.head')
  <!-- END HEADER -->
</head>

<body class="pace-black  mac desktop pace-done">
  <div class="pace  pace-inactive">
    <div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
      <div class="pace-progress-inner"></div>
    </div>
    <div class="pace-activity"></div>
  </div>
  <!-- BEGIN HEADER -->
  @include('partials.navbar')
  <!-- END HEADER -->
  <section class="m-t-100 sm-m-t-30">
    <!-- START CONTACT SECTION -->
    <section class="container container-fixed-lg p-t-40 p-b-80  sm-p-t-40 sm-p-b-20">
      <h4>Join WAC Now!<br></h4>
      @if (Session::has('message'))
      <div class="alert alert-info">
        <h5> {{ Session::get('message') }} </h5>
      </div>
      @endif
      <div class="col-md-8 order-md-1">
        <form class="needs-validation" role="form" action="{{ route('membership.store') }}" method="post" enctype="multipart/form-data" id="payment-form">
          {{ csrf_field() }}
          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="firstName">First name</label>
              <input type="text" class="form-control" id="fname" required name="fname">
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <input type="text" class="form-control" id="lname" required name="lname">
            </div>
          </div>

          <div class="row">
            <div class="col-md-12 mb-3">
              <label for="bio">Bio Data</label>
              <textarea class="form-control" rows="5" id="bio" name="bio"></textarea>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" required name="email">
            </div>
            <div class="col-md-6 mb-3">
              <label for="password">Password</label>
              <input type="password" class="form-control" id="password" required name="password">
            </div>
          </div>
          <div class="row">
          <div class=" col-md-6 mb-3">
            <label for="photo">Profile's Photo</label>
            <input type="file" class="form-control" id="photo" name="photo">
          </div>
          <div class=" col-md-6 mb-3">
            <label for="website">Website</label>
            <input type="url" class="form-control" id="website" name="website">
          </div>
          </div>
          <div class="mb-3">
            <label for="phone">Contact Number</label>
            <input type="tel" class="form-control" id="phone" name="phone" required>
          </div>
          <div class="mb-3">
            <label for="address">Address Line 1</label>
            <input type="text" class="form-control" id="address" name="address">

          </div>

          <div class="mb-3">
            <label for="address2">Address Line 2 <span class="text-muted">(Optional)</span></label>
            <input type="text" class="form-control" id="address2" name="address2">
          </div>
          <div class="mb-3">
            <label for="town">Town</label>
            <input type="text" class="form-control" id="town" name="town">
          </div>
          <div class="mb-3">
            <label for="postcode">Postcode</label>
            <input type="text" class="form-control" id="postcode" name="postcode">
          </div>
          <div class="form-group">
                        <label for="card-element">Credit Card</label>
                        <div id="card-element">
                          <!-- a Stripe Element will be inserted here. -->
                      </div>

                      <!-- Used to display form errors -->
                      <div id="card-errors" role="alert"></div>
                    </div>

                    <div class="spacer"></div>
          <div class="d-block my-3">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info" required name="aggreement">
              <label class="custom-control-label" for="save-info">I have read and agree to the members responsibilities
                (below):</label>
            </div>
          </div>

          <hr class="mb-4">
          <h4 class="mb-3">WAC Memebers Responsibilities</h4>
          <p>WAC is an organisation which relies on mutual trust and the willingness to share ourselves. All members
            are responsible for ensuring the confidentiality and safety that facilitates such trust and sharing. It is
            essential that every effort is made to maintain the confidentiality of the group.</p>
          <p>On joining WAC and ecruing your password protected account, you will have access to the Members Area
            containing the Memerbship list. Please note members details will be visible to other Members from this
            page. If you DO NOT agree to this please contact the Membership Secretary via the contact drop down fom to
            have your details removed from the list.</p>
          <p>The members’ names, addresses, e-mail and telephone numbers on the membership list may not be disclosed to
            anyone who is not a member of WAC. Use of the membership list for publicity for events other than those
            organised by WAC could contravene the Data Protection Act</p>
          <p>Any member who feels aggrieved or has a concern with another member may approach the Committee either
            directly or through the Local Group Contact.</p>
          <p>Each member is to ensure that the annual subscription is paid up to date.</p>
          <p>On leaving WAC it is the final responsibility of all members to return or destroy all membership lists and
            any documents including membership information.</p>
          <input type="submit" value="Register" class="btn btn-primary btn-lg btn-block">
        </form>
      </div>
    </section>
    <!-- END CONTACT SECION -->

    <!-- BEGIN SCRIPTS -->
    @include('partials.scripts')
    <!-- END SCRIPTS -->
  </section>
</body>

</html>